### PR TITLE
Add Hetzner Online as mail provider

### PR DESCRIPTION
**Pull request by n-se**
This adds mail.your-server.de (Hetzner Online) to the provider list

--
* Did you read the [contributing section](https://github.com/M66B/FairEmail#contributing)?
Yes
* Do you agree to [the license and the copyright](https://github.com/M66B/FairEmail#license)?
Yes

### CODE REVIEW

**Comment by M66B** [comment]
Thanks. Did you test this configuration?

**Comment by n-se** [comment]
Yes.

**Comment by M66B** [comment]
This will be part of the next beta release.

**Comment by n-se** [comment]
After some more testing I actually noticed a bug (that may also happens with other providers). On a fresh and newly created mailbox the folders are missing. They are not on the server (yet) and FairEmail does not create them.
For example K9-Mail and Thunderbird takes care of that and creates at least Inbox and Sent/Outbox.

**Comment by M66B** [comment]
IMHO an email client should never create folders without user interaction.

Accounts are supposed to always have at least an inbox. RFC 3501 even says "*It is an error to attempt to create INBOX*".

Only an inbox should be sufficient to setup an account and it would be a bug if this was not the case.

**Comment by n-se** [comment]
> IMHO an email client should never create folders without user interaction.

Noted (a lot do, though).

An Inbox (receiving works) is created but nothing else, therefore sending does not work ("A drafts folder is required to send messages"). But after your reply this looks like intended behavior of FairEmail. Thank you.

**Comment by M66B** [comment]
When needed you can create the required folders with FairEmail after setting up the account. For an account an inbox folder is required: for an identity a drafts folder of required.

Note that you'll create user folders in contrary to system folders (draft, sent, archive, etc), which is another reason why the server should do this.

**Pull request merged**
