### PR TITLE
Bugsnag is analytics

### PR DESCRIPTION
**Pull request by licaon-kter**
...and it brings some sort of tracking when (even if anonymous) a report is submitted, right?

### CODE REVIEW

**Comment by M66B** [comment]
Bugsnag is disabled by default and you'll be asked if you want to enable this on first run. There is an info button which leads to [this FAQ](https://github.com/M66B/FairEmail/blob/master/FAQ.md#user-content-faq104) with detailed information about what Bugsnag does.

You could see error reporting as a form of [Analytics](https://en.wikipedia.org/wiki/Analytics), but in my interpretation it should be used for marketing to be called Analytics, which it isn't. Tracking is in my idea even a step further and requires data to be not anonymous.

Bugsnag is disabled by default and explicitly opt-in, so there is no analytics and no tracking by default. Therefore I like to keep the description as simple as it is now. Agreed?

**Comment by M66B** [comment]
Error reporting haven proven to be very useful so far, but after things I have stabilized I am planning to remove Bugsnag.

**Comment by licaon-kter** [comment]
I do agree that it is useful, just that the description line, **at this moment**, is rather half-true. :)

Ref: https://forum.f-droid.org/t/eu-faircode-email-contains-bugsnag-needs-tracking-antifeature/6793

**Comment by M66B** [comment]
I like to be 100 % transparent, so I have changed the description, but a little bit different than proposed. Is this okay for you?

**Comment by licaon-kter** [comment]
I guess, thanks.

**Comment by M66B** [comment]
I guess I have to thank you ;-)

**Comment by M66B** [comment]
I have commented in the F-Droid forum too, but my comment is awaiting moderation (maybe because I am a new member or maybe because of the links in the comment).

**Pull request closed without merging**
