### PR TITLE
Add Freedom Internet

### PR DESCRIPTION
**Pull request by TheLastProject**
New/Upcoming Dutch ISP from the roots of XS4ALL

# Important

* Did you read the [contributing section](https://github.com/M66B/FairEmail#contributing)? yes
* Do you agree to [the license and the copyright](https://github.com/M66B/FairEmail#license)? yes

### CODE REVIEW

**Comment by M66B** [comment]
Did you test these settings?

Dutch: misschien kun je contact opnemen op marcel@faircode.eu voor overleg.

**Comment by TheLastProject** [comment]
Yup, tested and working, sent you an email through FairEmail from my freedom.nl account to confirm :)

**Comment by M66B** [comment]
I didn't receive your message so far ...

**Comment by TheLastProject** [comment]
Hmm, odd. I've successfully emailed to another of my accounts from my freedom.nl account and it arrived instantly.

**Comment by M66B** [comment]
Maybe a typo? marcel@faircode.eu

**Pull request merged**
