### PR TITLE
Update providers.xml

### PR DESCRIPTION
**Pull request by Primokorn**
Adding Orange.fr, the n°1 FR ISP provider.

# Important

* Did you read the [contributing section](https://github.com/M66B/FairEmail#contributing)? Yes
* Do you agree to [the license and the copyright](https://github.com/M66B/FairEmail#license)? Yes

### CODE REVIEW

**Comment by M66B** [comment]
To be sure: did you check if this configuration works?

**Comment by Primokorn** [comment]
Yes, just did it a few minutes ago. Orange doesn't support push messages though (information within your app).

**Comment by M66B** [comment]
Push messages is optional. Does both receiving and sending messages work?

**Comment by Primokorn** [comment]
Yes, tested too.

**Comment by M66B** [comment]
Thanks!

**Pull request merged**
