### PR TITLE
[WIP] Base themes on material components themes

### PR DESCRIPTION
**Pull request by proletarius101**
Currently the themes are based on AppCompat themes, which is the Android 7.0 style. This PR aims to make themes base on `Theme.MaterialComponents.DayNight.NoActionBar`, which gives the following advantages:
- Auto switching dark themes following the system. I know there is already such functionality. It just avoids any hacky way to do so. Of course, turning off `follow system` theme still works.
- More modern look, for free (without many modifications)

Before I do any substantial work, let me know your opioion ;)

### CODE REVIEW

**Comment by M66B** [comment]
Actually, I have avoided this.

More modern look also means fancy colored buttons, etc and not everybody will be happy with this, to say the least. Also, this doesn't fit into the minimalistic, non-distracting design.

The intention is being appreciated though.

**Comment by proletarius101** [comment]
> Actually, I have avoided this.
> 
> More modern look also means fancy colored buttons, etc and not everybody will be happy with this, to say the least. Also, this doesn't fit into the minimalistic, non-distracting design.
> 
> The intention is being appreciated though.

I have to say there won't be many visable changes through this, just subtle ones. I don't believe it could be say as "distracted", unless it's already so.

**Comment by M66B** [comment]
You are welcome to finish this and after that I will check how it looks like. Is that a solution?

**Comment by xcffl** [comment]
Yeah. At least that will enable me to easily customize the themes for my personal use while keeping tracking on your code

**Comment by proletarius101** [comment]
Yes. At least I'll be able to easily customize the themes while keeping tracking on you latest code then.

**Comment by M66B** [comment]
I might merge is after all, so I will reopen this.
Note that there are a number of buttons, for example in the setup screen, which deliberately have a distinguishing color.

**Comment by proletarius101** [comment]
Ok. And I'm not intended to change the color scheme.

-------- Original Message --------

**Comment by proletarius101** [comment]
Although I'm not intended to _change_ the color scheme, I found some inconsistencies. 
1. The material color tool tells me the color combination for your orange-blue theme should be: https://material.io/resources/color/#!/?view.left=0&view.right=1&primary.color=039be5&secondary.color=ffb300&secondary.text.color=000000. The recommended text color is black, which takes text legibility into account, whereas the current onPrimary text color is white. Should I listen to the color tool as  it seems you are following the material guidelines, and white color in that case is not that legible.
2. The button color you use is primarily gray. Is that intentional or simply the default color? The default color has become `colorPrimary`. Of course, I can deliberately set that color.

**Comment by M66B** [comment]
The text color is inherited from the base theme (light or dark). Pure black on a light background is very ugly and will most certainly result in complaints. Moreover, it wouldn't be consistent with the other themes.

See my earlier remarks about the buttons. The default button color is grey, as it's always has been in Android. I am not sure if colored buttons will be appreciated. Too many people hate change as well.

**Comment by proletarius101** [comment]
The text color is not inherited from the base theme, nor should it be, because there are backgrounds with different colors. Here I'm only talking about the text color on the primary colors. The primary is blue in this theme, and could be others in other themes. So it's on the blue background only. It will be less legible if it's white texts, and looks better in my opinion. But if you insist, I can keep it. I'll propose other color scheme in another PR anyway (or at least in my fork)

What I'm talking about is the default button color has been colored by the colorPrimary since Android 7.0 which is about 5 yrs ago. And would you like to be comply with the same color setting as the system? If no, of course I can set it as grey.
-------- Original Message --------

**Comment by M66B** [comment]
Maybe we talk about different things.

The text color is never blue, always dark or light depending on the background.

The background is never blue either, always dark or light.

So, I don't understand what you mean appearantly.

**Comment by proletarius101** [comment]
> Maybe we talk about different things.
> 
> The text color is never blue, always dark or light depending on the background.
> 
> The background is never blue either, always dark or light.
> 
> So, I don't understand what you mean appearantly.

See the link: https://material.io/resources/color/#!/?view.left=0&view.right=1&primary.color=039be5&secondary.color=ffb300&secondary.text.color=000000 The top app bar is blue. The text on the top app bar is black, which is not the case in your code.

**Comment by M66B** [comment]
I see.

Besides that I think it is ugly, it is not a good idea to change this in this stage of the project anymore. As said earlier, some people hate change.

**Comment by proletarius101** [comment]
>  As said earlier, some people hate change.

I see. I will make this in the most conservative way then.

**Comment by M66B** [comment]
Thanks for your understanding.

There will be a number of benefits by using the material theming though because there are a number of views/controls that are not available in Android and can be useful.

**Comment by M66B** [comment]
It seems to me that you put quite some work into this, so thanks!

Can you do a quick course of the color names mappings (classic / material) ?
It seems 'accent' is now called 'secondary' for example, correct?

**Comment by proletarius101** [comment]
> It seems to me that you put quite some work into this, so thanks!
> 
> Can you do a quick course of the color names mappings (classic / material) ?
> It seems 'accent' is now called 'secondary' for example, correct?

Bascially:
Accent -> Secondary, you are right.
PrimaryDark -> PrimaryVariant

And primarily you only need 6 colors to define a theme: colorPrimary, colorPrimaryVariant, colorOnPrimary, colorSecondary, colorSecondaryVariant, colorOnSecondary

Very short tutorial FYI: https://material.io/develop/android/theming/color

**Comment by M66B** [comment]
Thanks for the link, very useful!

**Comment by M66B** [comment]
I have tried the changes so far.

A few remarks, which you are probably aware of, so consider this more as a to-do list:

* Top action bar: navigation menu icon, title, icons and overflow menu have inconsistent light/black colors
* The dialog actions (ok, cancel, etc) are dim

I will keep using this for a while and if needed add comments here.

**Comment by proletarius101** [comment]
And dark/light/follow system switch has some problems.

**Comment by M66B** [comment]
It should be possible to fix dark/light/system with *AppCompatDelegate.setDefaultNightMode* in *ActivityBase*.

I guess *MODE_NIGHT_NO* needs to be set for all light/dark themes, which doesn't happen yet.

The "light", "dark", "system" theme names are legacy theme names.

Something like if(theme.contains("system")) is probably the simplest.

**Comment by M66B** [comment]
How about:

```
            String theme = prefs.getString("theme", "blue_orange_system");

            if (theme.contains("system")) {
                // `Set by Battery Saver` for Q above (inclusive), `Use system default` for Q below
                // https://medium.com/androiddevelopers/appcompat-v23-2-daynight-d10f90c83e94
                AppCompatDelegate.setDefaultNightMode(Build.VERSION.SDK_INT < Build.VERSION_CODES.Q ?
                        AppCompatDelegate.MODE_NIGHT_AUTO_BATTERY : AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM);
            } else
                AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO);
```

**Comment by proletarius101** [comment]
That looks great!
-------- Original Message --------

**Comment by M66B** [comment]
If you use XMPP or Signal, we can chat if you wish.
You can contact me [via here](https://contact.faircode.eu/?product=other) to setup a channel.

**Comment by M66B** [comment]
I guess there needs to be contain("light") and contains("dark") too to set MODE_NIGHT_NO/YES.

**Comment by M66B** [comment]
Re-basing to https://github.com/M66B/FairEmail/tree/material_theme

**Pull request closed without merging**
