### PR TITLE
Allow to edit search query

### PR DESCRIPTION
**Pull request by Unpublished**
In case of a typo or too many results this allows to quickly edit the query.

### CODE REVIEW

**Comment by M66B** [comment]
Although I appreciate the pull request I don't think this is a good idea because this is not how the search view is supposed to work.

**Comment by Unpublished** [comment]
Thanks for your feedback, but I can't quite follow yet.

Maybe not the native search view but a few mail clients and even Play Store make it work like this. Therefore I missed this behavior in FairEmail.

**Comment by M66B** [comment]
IMHO most people expect the search to be cleared when closed, which is also the default behavior of the search view.

What the Play store and likely other apps do is using a search history, which is a bit different. We can talk about implementing this instead. Note that FairEmail has search suggestions based on subjects already. Maybe the history can be added to the special searches.

**Comment by Unpublished** [comment]
> IMHO most people expect the search to be cleared when closed, which is also the default behavior of the search view.

I agree!
The query is still cleared when leaving the search.
This PR just persists it during a search.

Maybe you got the intention of this PR wrong, can you give this PR a try?
Then you'll see:
1. Search a query
2. Amend the search query by clicking the (new in this PR) search symbol and submit
3. Go back and try another search->The query is empty.

**Comment by M66B** [comment]
@Unpublished can you please check if the referenced commits do what you want?

**Comment by Unpublished** [comment]
@M66B
These commits only satisfy one use case (searching for the last query again).
Not the uses described in the description of this PR (fixing a typo in the last query or adjusting the query for better results).

**Comment by M66B** [comment]
I am afraid that editing the last query and using suggestions don't go together.

**Comment by Unpublished** [comment]
Technically it's possible: https://github.com/Unpublished/open-source-email/commit/3c3096f0588872e27708eac870c4e8e0cd9f0e48

But I think this makes UX rather inconsistent. Anyway I'm fine with applying my [approach](https://github.com/M66B/FairEmail/compare/master...Unpublished:editableSearchQuery) locally.

Thanks again for your work. It at least reduced the diff :grin:

**Comment by M66B** [comment]
Given that somebody sometimes want to edit a previous search query, I think this inconsistency is acceptable. See new commit above ;-)

**Pull request closed without merging**
