### PR TITLE
Try to find our correct identity when replying to event invites

### PR DESCRIPTION
**Pull request by t-8ch**
I confirm to have read the contribution and licensing/copyright information.

### CODE REVIEW

**Comment by M66B** [comment]
The idea is good, but this needs to be done in another way.
I will address this after I am finished with another change.

**Comment by t-8ch** [comment]
Ok, thanks!

**Comment by M66B** [comment]
Can you please check if my commit works for you?

**Comment by t-8ch** [comment]
Looks good, thanks!

**Pull request closed without merging**
